title: Mechanical Engineering
description: Open-source learning resources for mechanical engineering
theme: minima

header_pages:
  - alignment.md

plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs